# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

lang: tr-TR

# https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Istanbul

title: 𐱅𐰭𐰼𐰃:𐰸𐰆𐱃:𝟏𝟗𝟐𝟑

tagline: Mengü Tengri'nin gücüyle...

description: Eskiden beri neysek sonsuza kadar oyuz!
  
url: "https://www.tengrikut1923.com"

social:
  name: 𐱅𐰭𐰼𐰃:𐰸𐰆𐱃:𝟏𝟗𝟐𝟑
  links:
    - https://www.tengrikut1923.com

google_site_verification: B-IiQacda1RM8Z9GRYJ4iQ6YIJfzOvXA1L78g07arfU

google_analytics:
  id: G-6CR6XZ7ST2

theme_mode: dark

img_cdn:

avatar: "https://avatars.githubusercontent.com/u/40695466"

toc: true

comments:
  active: 'giscus'
  giscus:
    repo: tengrikut1923/tengrikut1923.github.io
    repo_id: 737562869
    category:
    category_id:
    mapping: 'pathname'
    input_position: 'bottom'
    lang: 'tr'
    reactions_enabled: '1'

pwa:
  enabled: true

paginate: 10

baseurl: ""

plugin-vars:
  {% href {{django-github}}/django/core/management/__init__.py#L398-L401
  django.core.management.execute_from_command_line %}

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - rollup.config.js

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
